image: maven:3.6-jdk-11

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - mvn clean install
    - mv recipes-rendered public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

compile:
  script:
    - mvn clean install
    - mv recipes-rendered public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'

addrecipe:
  script:
    - echo "Add recipe $RECIPE_URL"
    - mvn test -pl testbench -Dtest=ImportRecipeTest
  rules:
    - if: '$TRIGGER_PAYLOAD'

merge_request:
  stage: deploy
  script:
    - git checkout main
    - git merge --no-ff "$CI_COMMIT_REF_NAME" || exit 0
    - git push origin main
  only:
    - branches
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "web"'
  after_script:
    - |
      if [ "$CI_COMMIT_BRANCH" != "main" ] && [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ]; then
        # Create a merge request
        git checkout -b merge-request-$CI_COMMIT_BRANCH
        git push origin merge-request-$CI_COMMIT_BRANCH
        curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
          --data "source_branch=$CI_COMMIT_BRANCH" --data "target_branch=main" \
          --data "title=Merge $CI_COMMIT_BRANCH" \
          --data "remove_source_branch=true" \
          "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests"
      fi