image: maven:3.6-jdk-11

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - mvn clean install
    - mv recipes-rendered public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

compile:
  script:
    - mvn clean install
    - mv recipes-rendered public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'