image: maven:3.6-jdk-11

#stages:
#  - build
#  - scheduled

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
#  stage: build
  script:
    - mvn clean install
    - mv recipes-rendered public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
#      changes:
#        compare_to: 'refs/heads/main'
#        paths:
#          - '*'


addrecipe:
#  stage: build
  script:
    - echo "Add recipe $RECIPE_URL"
    - mvn test -pl testbench -Dtest=ImportRecipeTest
  rules:
    - if: '$TRIGGER_PAYLOAD'

#generate_meal_plan:
#  stage: scheduled
#  script:
#    - echo "This job runs every Sunday at noon"
#    - mvn test -pl testbench -Dtest=ImportRecipeTest
#  only:
#    - schedules